### ISSUE TITLE
Add a setting to disable git/github panels from appearing at startup on Windows

### ISSUE THREAD

**Issue by coldReactive** [pulsar-edit/github#41]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Add a setting to disable git/github panels from appearing at startup on Windows. Attached video shows the panels re-appearing after closing them and restarting the program. There's no file contents in the middle, as I have no files open, which is why the Github panel takes up the entire screen when Pulsar opens.

https://github.com/pulsar-edit/github/assets/1313673/4549f213-151e-45bd-b7e1-73cbce5005c5

### What benefits does this feature provide?

The ability to have less panels appearing on startup while not needing to disable the github packages.

### Any alternatives?

No.

**Comment by DeeDeeG** [comment]
I believe we managed to resolve this one on Discord a bit after this issue was posted. To recap:

This video shows how to put Git and GitHub tabs off in a sidebar. Sidebars _should_ stay minimized after being minimized to the side.

https://github.com/pulsar-edit/github/assets/20157115/026c6289-113f-47bc-aaab-a45577f32720

Also: tree-view side pane is a bit "special" in that it always shows itself, unless you enable the following preference: "Settings --> Packages --> Tree View --> Hidden On Startup".
